### PR TITLE
Prepare 1.16.5

### PR DESCRIPTION
**Pull request by Andre601**
This is a rather minor edit as it only adds 1.16.5 to the `depends.minecraft` version.

Right now is this only to make the Fabric mod loader start without any errors. Optifine itself isn't updated yet for 1.16.5 and will give back an unsupported version error for OptiFabric.

So if at all should this PR only be merged once Optifine has a 1.16.5 version released, which I hope won't take forever...

### CODE REVIEW

**Comment by xb2016** [comment]
It will work if you update your OptiFine to 1.16.5: https://optifine.net/downloads

**Comment by Andre601** [comment]
> It will work if you update your OptiFine to 1.16.5: https://optifine.net/downloads

It funny enough wasn't there yet when I made this minor PR.
However, the OptiFabric still needs this update here as otherwise Fabric will print an error about a required version not being mentioned.

**Review by markotomcik — APPROVED** [review]

**Comment by jrvgr** [comment]
this worked

**Review by untodesu — CHANGES_REQUESTED** [review]
Using `>=` sequence would be much easier and shouldn't cause any similar issues in future.
So I'd change this:
```json
    "minecraft": ["1.16.1", "1.16.2", "1.16.3", "1.16.4", "1.16.5"],
```
to this:
```json
    "minecraft": ">=1.16.1",
```

**Comment by lordofpipes** [comment]
> ```json
>     "minecraft": ">=1.16.1",
> ```

This is a poor idea for Optifabric, most changes from Mojang and from Optifine are more than just a few lines of code. It's quite rare for Mojang to release such a small patch.

**Comment by untodesu** [comment]
> This is a poor idea for Optifabric, most changes from Mojang and from Optifine are more than just a few lines of code. It's quite rare for Mojang to release such a small patch.

As far as I know, it isn't.
And the Optifine itself is the reason: without FML it is being loaded directly to the game using launcher profiles so if I understand correctly, OptiFabric does suddenly the same but a bit after the game startup so I don't think there's something bad about that

**Pull request closed without merging**
