### PR TITLE
Fix renderBlock call in lower versions (<=1.18.2)

### LINKED ISSUE #983: 7d01086833 breaks 1.18.2 + Fabric API 0.75.1
The game crashes as soon as you load into a world, be it single or multi player. As far as I tested this seems to be caused by the `trailingBoolean` stuff added to `ChunkRendererFix`, as removing this particular change does not cause any issue in <1.19.3 (however it does break 1.19.3 in the same manner described).

These are the important bits of the stacktrace:
```
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_846$class_851$class_4578 failed
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hookChunkBuildTesselate(Lnet/minecraft/class_776;Lnet/minecraft/class_2680;Lnet/minecraft/class_2338;Lnet/minecraft/class_1920;Lnet/minecraft/class_4587;Lnet/minecraft/class_4588;ZLjava/util/Random;)Z in fabric-renderer-indigo.mixins.json:MixinChunkRebuildTask from mod fabric-renderer-indigo failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-renderer-indigo-refmap.json
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_3146(String)" because "this.field_3690.field_1724" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_31549()" because "$$1" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3690.field_1724" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_31549()" because "$$1" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3690.field_1724" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_3130()" because "this.field_3690.field_1724" is null
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_18798()" because "$$1" is null
```

### PR DESCRIPTION
**Pull request by XXMA16**
Fixes a bug introduced in 7d01086 that causes `ChunkRendererFix` to look for `java/util/Random` at the wrong index inside the arguments of `renderBatched` in  1.18.2 (and maybe other versions as well, although I have not checked).

I have not done extensive testing and can only say for sure this does not break 1.18.2, 1.19.2 and 1.19.3 with Fabric API 0.75.1, but I suppose the worst case scenario would be the bug persisting in other versions, without breaking things that worked fine previously.

fixed #983

### CODE REVIEW

**Comment by Chocohead** [comment]
This is indeed the mistake, running with assertions turned on with `-ea` confirms that.

There is an implicit assumption that there is always an `IModelData` 20 lines after your changes, it always removes the load instruction for it. It was skipping this extra parameter which `ChunkRendererFix` was originally made to do. As a result this PR might as well be
```java
assert "net/minecraftforge/client/model/data/IModelData".equals(args[end].getInternalName());
end--;
```

**Comment by XXMA16** [comment]
I messed stuff up and accidentally deleted the original commit while trying to get my fork in sync (after making some redundant merges and commits). Sorry for the inconvenience.

**Comment by XXMA16** [comment]
I tested the following versions with the latest Fabric API available for each and they all seem to be working fine:
- 1.19.3
- 1.19.2
- 1.18.2
- 1.16.5
- 1.16.1

**Comment by Chocohead** [comment]
Very nice, thanks for your work on this.

I've got imminent plans to vastly reduce the inconvenience of needing to manually test so many potential setups which should stave off issues like this from reoccurring.

**Pull request merged**
