### PR TITLE
Added 1.18 to the list of supported versions

### PR DESCRIPTION
**Pull request by redpandamonium**

### CODE REVIEW

**Comment by redpandamonium** [comment]
It seems to work out of the box if it is allowed to run. Did not do extensive testing but it does launch without errors.

**Comment by backryun** [comment]
not working, issue #478

**Comment by juliocoliveira** [comment]
It seems that just updating the fabric mod file does not fix it, It is crashing when loading a world with fabric api and other mods.
#480 #478

**Comment by unmoving-javi** [comment]
Same issue here, no clue why though.

**Pull request closed without merging**
