### PR TITLE
Add support for 1.17.1

### PR DESCRIPTION
**Pull request by Alliegaytor**
There aren't any optifine builds for 1.17.1 yet, but this should work when one is made

### CODE REVIEW

**Comment by ASchneider-GitHub** [comment]
Just wanted to confirm that adding `"1.17.1"` to the `fabric.mod.json` file (as mentioned in the PR) works, and the mod loads [OptiFine HD U G9 pre26](https://optifine.net/downloads) correctly

**Review by MelonHell — COMMENTED** [review]
thanks you

**Comment by MelonHell** [comment]
> 
> 
> Just wanted to confirm that adding `"1.17.1"` to the `fabric.mod.json` file (as mentioned in the PR) works, and the mod loads [OptiFine HD U G9 pre26](https://optifine.net/downloads) correctly

Yes, it works correctly

**Comment by JohnFawkes** [comment]
can someone whos built OptiFabric themselves with the change, please provide a jar? I tried building it myself but it fails

**Comment by JohnFawkes** [comment]
maybe just put the jar in one of your repos under releases?

**Comment by MelonHell** [comment]
> 
> 
> can someone whos built OptiFabric themselves with the change, please provide a jar? I tried building it myself but it fails

just open OptiFabric jar in winrar or 7zip and change fabric.mod.json

**Review by thewilloftheshadow — APPROVED** [review]

**Comment by Ari-43** [comment]
You don't even need WinRAR or 7zip to do this. You just rename the jar to a zip, extract, edit, and then zip the contents of the folder and rename the new zip to a jar.

**Comment by Hellster90** [comment]
I did the change in the json file for getting it to work in 1.17.1, but Optifine has lost it's customization buttons etc in Video Settings, so might be better waiting for an official release for 1.17.1

**Pull request closed without merging**
