### PR TITLE
Bump Fabric ASM version

### PR DESCRIPTION
**Pull request by PlanetTeamSpeakk**
It is required for compatibility with my mod [PlanetTeamSpeakk/MoreCommands](https://github.com/PlanetTeamSpeakk/MoreCommands)

### CODE REVIEW

**Comment by Chocohead** [comment]
You'd be best putting `"mm": ">=2.3"` in the `depends` of your `fabric.mod.json` to ensure you always have the minimum version you need loaded rather than trusting it will be provided anyway or picked out of the jar-in-jar options by Loader. I'll happily bump it in OptiFabric all the same though

**Comment by PlanetTeamSpeakk** [comment]
I include the mod using shadowjar as including it via jar-in-jar somehow makes the mod not load in a dev environment, or at least not soon enough. But yes, I will require it in my fabric.mod.json but seeing as many people use this mod and this mod uses mm 2.2 rather than 2.3, it breaks my mod which is no good.

**Comment by Chocohead** [comment]
It's a bit strange you'd need to shadow, did you remember to still add Fabric ASM with a `modImplementation`/`modApi`/etc. when you added it as an `include`?

**Comment by PlanetTeamSpeakk** [comment]
Yeah I did, but it completely broke everything I was doing with the library for some reason, shadowing seems to be the only working method.

**Pull request closed without merging**
